
#ifndef SCALER_ERRCODE_H
#define SCALER_ERRCODE_H

enum ErrCode {
    FUNC_NOT_IMPLEMENTED = -1,
    PATH_FORMAT_INCORRECT = -2,
    ELF_SYMBOL_NOT_FOUND = -3,
    ELF_FILE_CANNOT_OPEN = -4,
    CANNOT_OPEN_PROCMAP = -5,
    MEM_ALLOC_FAIL=-6,
    ELF_FILE_NOT_COMPATIBLE=-7,
    ELF_SECTION_NOT_FOUND = -8,
    ELF_SEGMENT_NOT_FOUND = -9,
    CANNOT_READ_PROCESSMEMORY =-10,
    ELF_SECTION_NOT_FOUND_IN_MEM = -11,
    ELF_DYNAMIC_ENTRY_PARSE_ERR = -12,
    CANNOT_CHANGE_PERMISSION = -13,
    WRONG_INTERFACE=-14,
    CONFIG_PARSE_FAILED=-15,
    COMPILATION_FAILED=-16,
    HANDLER_LOAD_FAILED=-17,
    NO_HANDLER_IN_DLL=-18,
    UNKNOWN_SIGNAL=-19,
    PTRACE_FAIL=-20,
    TARGET_EXEC_FAIL=-21,
    PTRCTL_FAIL=-22,
    WAIT_FAIL=-23,
    CHILD_THREAD_EXITED=-24,
    UNEXPECTED_STOP=-25,
    UNRECOGNIZSBLE_INSTR=-26,
    SIGINT_HANDLER_REG_FAIL=-27,


};

#endif //SCALER_ERRCODE_H
