app:
  name: ScalerAnalyzer
  version: ${project.version}

grpc:
  server:
    port: 3060

spring:
  neo4j:
    uri: "bolt://127.0.0.1:7687"
    authentication:
      username: "neo4j"
      password: "test"

log4j.rootLogger: DEBUG, stdout
log4j.appender.stdout: org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout: org.apache.log4j.PatternLayout

log4j.category.org.springframework.data.neo4j: DEBUG